version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_TAG=latest
      - ECR_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image using Docker Compose...
      - docker-compose build

  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag $IMAGE_REPO_NAME:latest $ECR_REPOSITORY_URI:$IMAGE_TAG
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
