version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production

  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
